var data1 = [
    ["NIS 호스트 관련 정보가 저장된 파일","hosts.byname"],
    ["부팅 시 필요한 서비스를 이 스크립트 안에 등록\n","/etc/rc.d/rc.local\n"],
    ["DNS 관련해서 bind 뜻은?\n","Bind : Berkeley Internet Name Domain, 설정이 쉬우면서도 표준을 따른다.\n"],
    ["웹페이지 인증을 위해 아파지 사용자를 만드는 과정에서 사용되는 명령어는?\n","htpasswd -c /usr/local/httpd/conf/passwd"],
    ["xinetd에서 생성하는 관련 데몬의 최대 개수를 제한 없음으로 지정하려고 한다. 어떤 항목을 수정해야 할까?\n","instances = Unlimited\n"],
    ["메일 서버가 사용하는 호스트를 등록하는 파일\n vi (괄호) \n ihd.or.kr \n kait.or.kr","/etc/mail/local-host-names"],
    ["rsyslog로 생성되는 로그파일의 생성 위치는?\n","/var/log\n"],
    ["NTP에서 날짜 및 시간을 맞추기 위해서 원격지 NTP를 이용하는 명령어","ntpdate"],
    ["VNC서버에서 해상도를 변경하는 파일로 알맞은 것은? VNC 설정 파일의 경로는?\n","/etc/sysconfig/vncservers\n"],
    ["시스템 초기화와 관련된 내용이 설정되어있는 파일의 경로는?\n","/etc/init/rcS.conf (/etc/rc.d/rc.sysinit 실행)\n"],
    ["\n시스템 하드웨어 정보 출력 명령어\n","\nlspci\n"],
    ["서버의 커널 변수를 제어하여 TCP 연결 상태를 3시간동안 유지하도록 변경하려고 한다. 명령어는?\n","echo 10800 > /proc/sys/net/ip4/tcp_keepalive_time\n"],
    ["파일을 백업하는 명령어 cpio 사용법","find /home | cpio -ocv > home.backup (/home아래에 있는 모든 파일들을 home.backup으로 백업하겠다.)"],
    ["아파치 소스 파일이 정상적으로 다운로드 되었는지 검증해 보려고 한다. 이 때 사용하는 명령어는?\n","md5sum ~\n"],
    ["DHCP 서버의 환경설정 파일 dhcpd.conf에서 게이트웨이 주소를 192.168.5.1로 변경하려고 한다. 명령어는?\n","option router 192.168.5.1;\n"],
    ["NIS 사용자 계정 관련 정보가 저장된 파일","passwd.byname"],
    ["모듈의 의존성을 편집해주는 명령어는?\n","depmod\n"],
    ["iptables의 테이블 중 넷필터의 연결 추적 시스템과 독립적으로 동작해야 하는 규칙을 설정하는 테이블은?\n","raw\n"],
    ["스왑파일을 만드는 명령어는? 블럭사이즈 1k, 총 1GB 만들기 \n","dd if=/dev/zero of=/swap-file bs=1k count=1024000\n"],
    ["ifconfig를 이용해서 ip를 변경하면 재시작시 모든 정보가 날아간다. 어떤 파일을 수정해야 재시작 후에도 변경된 ip가 유지 될까?\n","/etc/sysconfig/network-scripts/ifcfg-eth0\n"],
    ["/etc/fstab 설정법 중 NFS 등록 법은?\nNFS IP : 192.168.5.13\nNFS 공유 디렉터리명 : /nfsdata\nNFS 클라이언트에서 마운트할 디렉터리명 : /ndata\n","192.168.5.13:/nfsdata /ndata nfs\n"],
               
]